from __future__ import annotations

from enum import StrEnum


class WorkflowState(StrEnum):
    RECEIVE_REQUIREMENT = "RECEIVE_REQUIREMENT"
    VALIDATE_SCOPE = "VALIDATE_SCOPE"
    INSPECT_REPOSITORY = "INSPECT_REPOSITORY"
    PROPOSE_PLAN = "PROPOSE_PLAN"
    APPLY_MINIMAL_PATCH = "APPLY_MINIMAL_PATCH"
    RUN_TARGETED_TESTS = "RUN_TARGETED_TESTS"
    SUMMARIZE_EVIDENCE = "SUMMARIZE_EVIDENCE"
    STOP_FOR_HUMAN_REVIEW = "STOP_FOR_HUMAN_REVIEW"


WORKFLOW = tuple(state.value for state in WorkflowState)
